export FOX_BUILD_DEVICE=uke
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_DEFAULT_KEYMASTER_VERSION=4.1
export OF_PATCH_AVB20=1
export OF_MAINTAINER="yourname"
export FOX_USE_TWRP_SAR_DETECT=1
